[versions]
kotest = "6.0.0.M2"
kotlin = "2.1.21"
kotlin-gradle-plugin = "2.1.20"

[libraries]
clikt = "com.github.ajalt.clikt:clikt:4.4.0"
jline = "org.jline:jline:3.25.1"
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner-junit5       = { module = "io.kotest:kotest-runner-junit5",       version.ref = "kotest" }
kotlin-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-test-junit5         = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
mordant = "com.github.ajalt.mordant:mordant:2.3.0"

[bundles]
kotest-jvm          = ["kotest-assertions-core-jvm", "kotest-runner-junit5"]
kotlin-testing-jvm  = ["kotlin-test-junit5"]

[plugins]
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:5.1.7"
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.89.1"
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
taskTree = "com.dorongold.task-tree:4.0.1"

